---
title: "IS415 - Geovid - China"
author: "Ivy Hau, Shermin, Jasky"
date: "11/11/2020"
output: html_document
---
# Introduction

# Load Packages

```{r echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE}
packages = c('sp','tidyverse', 'sf',  'rgdal','spatstat', 'spatstat', 'raster', 'maptools', 'rgeos','dplyr', 'tmap', 'ggplot2', 'spdep', 'lubridate', 'tidygeocoder', 'leaflet', 'classInt')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

# Import Data

```{r echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE}
city_confirmed <- read_csv("data/aspatial/City_Confirmed_0115_1010.csv")
city_death <- read_csv("data/aspatial/City_Death_0115_1010.csv")
city_recover <- read_csv("data/aspatial/City_Recover_0115_1010.csv")
china_city <- st_read(dsn = "data/geospatial", layer = "china_city_basemap")
china_province <- st_read(dsn = "data/geospatial", layer = "china_province_basemap")
```


# EPSG:3415
```{r echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE}
china_3415 <- st_set_crs(china_city, 3415)
qtm(china_3415)
```

#Confirmed Cases in each City
```{r echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE}
city_confirmed_geo <- left_join(city_confirmed, china_3415, by = c('City_EN' = 'City_EN'))
city_confirmed_geo <- st_as_sf(city_confirmed_geo)

tm_shape(city_confirmed_geo)+
  tm_fill("T_C_09",
          style = "quantile",
          n = 10,
          palette = "Blues",
          legend.hist = TRUE, ) + 
  #tm_facets(by="month", free.coords=TRUE, drop.shapes=FALSE) +
  tmap_options(max.categories = 41) +
  tm_layout(main.title = "Distribution of Cases",
            main.title.position = "center",
            main.title.size = 1,
            legend.height = 0.40, 

            legend.width = 0.35,
            legend.outside = TRUE,
            legend.position = c("right", "bottom"),
            frame = TRUE) +
  tm_borders(alpha = 0.5)
```





